data-types:
	$(CC) -o data-types data-types.c


types-size:
	$(CC) -o types-size types-size.c

pointers:
	$(CC) -o pointers pointers.c

all: clean types-size pointers data-types

clean:
	rm -f *~ types-size pointers data-types

.PHONY: clean all
