data-types:
	$(CC) -o data-types data-types.c

types-size:
	$(CC) -o types-size types-size.c

pointers:
	$(CC) -o pointers pointers.c

macros:
	$(CC) -o macros macros.c

define:
	$(CC) -o define define.c

overflow:
	$(CC) -o overflow overflow.c

main:
	$(CC) -o main main.c

linkedlist:
	$(CC) -o linkedlist linkedlist.c

all: clean types-size pointers data-types define macros overflow main linkedlist

clean:
	rm -f *~ types-size pointers data-types define macros overflow main linkedlist

.PHONY: clean all
